name: Déployer le site web

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Installer Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible
      - name: Déployer le site web
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          ansible-playbook deploy.yml -e "GITHUB_TOKEN=$GITHUB_TOKEN GITHUB_ACTOR=$GITHUB_ACTOR GITHUB_REPOSITORY=$GITHUB_REPOSITORY"

