name: Déployer le site web

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Installer Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible
      - name: Déployer le site web
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ansible-playbook deploy.yml
